[project]
name = "simpleadder"
version = "0.1.0"
description = "Web service to Add two integer numers"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
	"fastapi",
	"uvicorn[standard]",
]

[project.scripts]
simpleadder = "uvicorn.main:main"
